spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret:
    access: vt3fI5kwBmGvDQPcUrNVkO+Iw/XC75OtH7JlcHlsIcQ=
    refresh: 57gzLd0XY1SJl/g29vSC8jT/UmHoLMC+18bwp+LiG0Q=
  expiration-time:
    access: 10
    refresh: 30